
[jobs.check]
command = ["cargo", "check"]

[jobs.clippy]
command = ["cargo", "clippy", "--all-targets", "--all-features"]

[jobs.test]
command = ["cargo", "nextest", "run"]

[jobs.all]
command = [
  "bash",
  "-c",
  "cargo clippy --all-targets --all-features && cargo nextest run"
]
need_stdout = true
